POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é meu primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos


###

PUT http://localhost:3333/videos/bae9d471-b5f5-46f4-a645-64bda13c5bbf
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é meu primeiro video",
    "duration": 180
}


###

DELETE http://localhost:3333/videos/bae9d471-b5f5-46f4-a645-64bda13c5bbf